## https://documentation.blackduck.com/ja-JP/bundle/bridge/page/documentation/c_github-blackduck.html

name: Black Duck Security Scan
on:
  push:
    branches:
      - main
      - test1

  pull_request:
    branches:
      - main
      - test1
      
jobs:
  blackducksca:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Security Scan FULL
        id: black-duck-security-scan-full
        uses: blackduck-inc/black-duck-security-scan@v2
        env:
          DETECT_PROJECT_NAME: Ueda_test
          DETECT_PROJECT_VERSION_NAME: GH_SecurityScan_Full
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          blackducksca_scan_full: true
          blackducksca_waitForScan: true
          mark_build_status: failure
          include_diagnostics: false
          blackducksca_prComment_enabled: true
          github_token: ${{ secrets.GH_TOKEN }}
          #blackducksca_reports_sarif_create: true
          #blackducksca_upload_sarif_report: true
  blackduckscaPRcomment:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Security Scan PR Comment
        id: black-duck-security-scan-PRcomment
        uses: blackduck-inc/black-duck-security-scan@v2
        env:
          DETECT_PROJECT_NAME: Ueda_test
          DETECT_PROJECT_VERSION_NAME: GH_SecurityScan_PRcomment
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          blackducksca_waitForScan: true
          mark_build_status: failure
          include_diagnostics: false
          blackducksca_prComment_enabled: true
          github_token: ${{ secrets.GH_TOKEN }}
  blackduckscaPR:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Security Scan PR
        id: black-duck-security-scan-PR
        uses: blackduck-inc/black-duck-security-scan@v2
        env:
          DETECT_PROJECT_NAME: Ueda_test
          DETECT_PROJECT_VERSION_NAME: GitHub_SecurityScan_PR
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          blackducksca_waitForScan: true
          mark_build_status: failure
          include_diagnostics: false
          blackducksca_fixpr_enabled: true
          blackducksca_fixpr_maxCount: 5
          blackducksca_scan_failure_severities: 'CRITICAL'
          github_token: ${{ secrets.GITHUB_TOKEN }}

