name: Black Duck Security Scan
on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master
      
jobs:
  blackducksca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Security Scan
        id: black-duck-security-scan
        uses: blackduck-inc/black-duck-security-scan@v2
        env:
    　　　DETECT_PROJECT_NAME: Ueda_test
    　　　DETECT_PROJECT_VERSION_NAME: GU_SecurityScanPR
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
          blackducksca_waitForScan: true
          mark_build_status: failure
          include_diagnostics: false
          blackducksca_prComment_enabled: true
          github_token: ${{ secrets.GH_TOKEN }}
          blackducksca_fixpr_enabled: true
          blackducksca_reports_sarif_create: true
          blackducksca_upload_sarif_report: true
